name: Build APK from Website

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL du site web'
        required: true
        default: 'https://ton-site.com'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate APK with PWABuilder
        uses: pwa-builder/action@main
        with:
          url: ${{ github.event.inputs.url }}
